### ISSUE TITLE
License change request

### ISSUE THREAD

**Issue by jfstephe** [cscott/compressjs#15]
Hi,
Any chance you could change this to an MIT license?
Thanks,
John

**Comment by n1474335** [comment]
Agreed. Any permissive licence would be greatly appreciated.

![image](https://user-images.githubusercontent.com/22770796/34524923-2358128a-f095-11e7-8fbf-de261d92a08f.png)

**Comment by cscott** [comment]
This would be a more compelling request if you included information about why you want this change.  To benefit another open source project?  To accomplish some good in the world?

**Comment by cscott** [comment]
More concretely, this project uses code adapted from other GPL projects; I'd have to get those relicensed before I could relicense my contribution. And I'd need to know why I should put in the effort to do that before doing it.

**Comment by jfstephe** [comment]
Apologies, I should have made this clearer. I would be wanting to use this in commercial non-open source projects.

I really don't want to get into an open-source vs commercial debate, I'm just trying to push forward the development of projects. My (small) company contributes to open source projects for bug fixes and new features and it's a shame not to be able to benefit from great software that fulfills general needs, such as this.

If you don't want to open it up that's entirely your call, I'm just trying to show that there are others in the commercial space that can't use this ATM and would potentially be able to contribute to your package. With the license as it stands at the moment this isn't possible.

**Comment by n1474335** [comment]
For my part, I would be interested in incorporating this into [CyberChef](https://github.com/gchq/CyberChef), which uses the Apache 2.0 Licence - incompatible with GPL.
