### ISSUE TITLE
Help needed for contribution

### ISSUE THREAD

**Issue by upupming** [cscott/compressjs#22]
Hi, I have created a new project [arithmetic-coding](https://github.com/upupming/arithmetic-coding) and finished the implementation. But now the biggest problem is to read/write to files, the speed is so slow. I'm going to find another method for reading/writing files.

As shown in [travis build log](https://travis-ci.com/upupming/arithmetic-coding/builds/106308877), my algorithm takes `1357ms` to encode and decode a `61,357B` file.

And so I find your project! I have a few questions now:
1. Is it okay for me to add my arithmetic coding algorithm to your project?
2. Also, should I reuse https://github.com/cscott/compressjs/blob/master/lib/Stream.js
3. Should I keep it a single project or integrate to this project directly?

Thanks for your patience in advance!

**Comment by cscott** [comment]
It's fine to build on my work! I'd recommend forking my project on GitHub
and working on your contribution there.  When it's done we can talk about
whether to merge the changes back into my repository, release it as a
separate npm package or what. I'm not actively maintaining compressjs these
days so it may make more sense to release your work as a separate package
but we don't have to decide that now.
  --scott

**Comment by upupming** [comment]
Thanks for quick response and I will work on it this weekend.

**Comment by upupming** [comment]
Closed as I have opened a PR #23.
