### ISSUE TITLE
Streaming interface

### ISSUE THREAD

**Issue by apla** [cscott/compressjs#6]
Hi!

I want to implement streaming interface for bz2 decompress, but don't understand what project I need to use, this one or https://cscott/compressjs/seek-bzip. Seems like you patching both, but there is difference between [seek-bzip's index.js](https://github.com/cscott/seek-bzip/blob/master/lib/index.js) and [compressjs's Bzip2.js](https://github.com/cscott/compressjs/blob/master/lib/Bzip2.js)

**Comment by cscott** [comment]
seek-bzip is much lighterweight, if you only need decompression, and it already contains an example of a streaming decompression interface: https://github.com/cscott/seek-bzip/blob/master/test/stream.js
